const Feed = require('feed').Feed
const description = require('description')
const memoize = require('fast-memoize')

const types = {
  blog: 'blog',
  releases: 'releases',
}

module.exports.setupFeed = memoize(async (type, items) => {
  let feed = new Feed({
    title: 'Electron',
    description:
      'Build cross platform desktop apps with JavaScript, HTML, and CSS.',
    id: 'https://www.electronjs.org/',
    link: 'https://www.electronjs.org/',
    generator: 'Electron website',
    feedLinks: {
      json: 'https://www.electronjs.org/releases.json',
      atom: 'https://www.electronjs.org/releases.xml',
      atom1: 'https://www.electronjs.org/blog/rss.xml',
    },
  })

  switch (type) {
    case types.releases:
      items.forEach((release) => {
        feed.addItem({
          title: `Electron v${release.data.version}`,
          id: `https://electronjs.org/releases#${release.data.version}`,
          date: new Date(release.data.created_at),
          link: release.data.html_url,
          content: release.data.body_html,
        })
      })
      break
    // No need for a blog type because it is generated by the new website infrastructure
    default:
      console.log(type === types.releases)
      throw new Error('Invalid rss feed type')
  }

  return feed
})
