#!/usr/bin/env node

const fs = require('fs')
const tmp = require('tmp')
const path = require('path')
const fetchDocs = require('../lib/fetch-docs.js')

const awesomeData = JSON.stringify(require('awesome-electron'), null, 2)
const awesomeFile = path.join(process.cwd(), '_data', 'awesome_electron.json')
fs.writeFileSync(awesomeFile, awesomeData)

var settings = {
  configFile: path.join(process.cwd(), '_config.yml'),
  tmpDir: tmp.dirSync().name,
  targetDir: path.join(__dirname, '..', '_docs')
}

fetchDocs(settings, function callback (error, message) {
  if (error) console.log(error)
  if (message) console.log(message)
})
