#!/usr/bin/env node

const ChildProcess = require('child_process')

console.log('Running lighthouse')

const server = ChildProcess.spawn('bundle', ['exec', 'jekyll', 'serve', '--baseurl', '', '--no-watch'])

server.on('error', (error) => {
  console.error('Error starting server')
  console.error(error.stack)
  process.exit(1)
})

server.stderr.on('data', (data) => {
  process.stderr.write(data)
})

let serverOutput = ''

server.stdout.on('data', (data) => {
  process.stdout.write(data)

  serverOutput += data

  if (serverOutput.includes('Server running')) {
    console.log('Server running, starting lightcrawler')
    lightcrawl()
  }
})

function lightcrawl() {
  const lightcrawlerPath = require.resolve('lightcrawler/cli.js')
  const lightcrawler = ChildProcess.spawn(lightcrawlerPath, ['--url', 'http://127.0.0.1:4000', '--config', 'lighthouse.json'], {stdio: 'inherit'})

  lightcrawler.on('error', (error) => {
    console.error('Error running lighthouse')
    console.error(error.stack)
    process.exit(1)
  })

  lightcrawler.once('exit', (code) => {
    server.kill()
    process.exit(code)
  })
}
