#!/usr/bin/env node

// Load SLACK_WEBHOOK from .env (for local testing)
require('dotenv').load()

const slack = require('slack-notify')(process.env.SLACK_WEBHOOK)
var input = ''

// Collect STDOUT and STDERR from release script
process.stdin
  .setEncoding('utf8')
  .on('readable', () => { input += String(process.stdin.read() || '') })
  .on('end', send)

function send () {
  if (!input.match('npm ERR') && !input.match('Test failed')) {
    return process.exit()
  }

  const opts = {
    icon_url: 'https://avatars0.githubusercontent.com/u/18403005?v=3',
    username: 'electron.atom.io',
    text: input
  }

  slack.send(opts, (err) => {
    if (err) throw err
  })
}
