#!/usr/bin/env bash

set -x            # print commands before execution
set -o errexit    # always exit on error
set -o pipefail   # honor exit codes when piping
set -o nounset    # fail on unset variables

rm -r precompiled || true
mkdir -p precompiled/scripts
mkdir -p precompiled/styles
node ./script/precompile-js
./node_modules/.bin/uglifyjs --compress --mangle -o precompiled/scripts/index.min.js -- precompiled/scripts/index.js
mv precompiled/scripts/index.min.js precompiled/scripts/index.js
node ./script/precompile-sass
