#!/usr/bin/env bash

set -x            # print commands before execution
set -o errexit    # always exit on error
set -o pipefail   # honor exit codes when piping
set -o nounset    # fail on unset variables

# clone the repo
git clone https://github.com/electron/electron.atom.io
cd electron.atom.io
npm install

# configure git
git config user.email "electron@github.com"
git config user.name "Electron Bot"

# run each build script independently and commit changes atomically
npm run build-versions
if [[ $(git status --porcelain) != "" ]]; then
  git add .
  git commit -avm "update versions"
fi

npm run build-releases
if [[ $(git status --porcelain) != "" ]]; then
  git add .
  git commit -avm "update releases"
fi

npm run build-docs
if [[ $(git status --porcelain) != "" ]]; then
  git add .
  git commit -avm "update docs"
fi

npm run build-userland
if [[ $(git status --porcelain) != "" ]]; then
  git add .
  git commit -avm "update userland"
fi

npm run build-awesome
if [[ $(git status --porcelain) != "" ]]; then
  git add .
  git commit -avm "update awesome"
fi

npm run build-apps
if [[ $(git status --porcelain) != "" ]]; then
  git add .
  git commit -avm "update apps"
fi

# test it all before pushing
npm test
git push origin gh-pages
