#!/usr/bin/env bash

set -x            # print commands before execution
set -o errexit    # always exit on error
set -o pipefail   # honor exit codes when piping
set -o nounset    # fail on unset variables

# Clone the repo
git clone https://github.com/electron/electron.atom.io
cd electron.atom.io
npm install
npm run build
npm test

# bail if no changes are present
[[ `git status --porcelain` ]] || exit

git add .
git config user.email "kevin+electronbot@github.com"
git config user.name "Electron Bot"
git commit -m "new build"
git push origin gh-pages

# clean up
cd ..
rm -rf electron.atom.io
