#!/usr/bin/env node

var fs = require('fs')
var request = require('request')

var token = process.env.ATOM_ACCESS_TOKEN || 'da809a6077bb1b0aa7c5623f7b2d5f1fec2faae4'
var options = {
  url: 'https://api.github.com/repos/electron/electron/releases',
  json: true,
  headers: {
    'user-agent': 'Electron',
    'Authorization': 'token ' + token
  }
}

request(options, function (error, response, body) {
  if (error) return console.log(error)
  if (response.statusCode == 200) {
    body = body.filter(function (release) {
      return !release.draft && !release.prerelease
    })

    body.forEach(function (release) {
      release.version = release.tag_name.substring(1)
      delete release.assets
      delete release.author

      // turn PR references like #123 into hyperlinks
      release.body = release.body.replace(
        / #(\d+)\r\n/gm,
        ' <a href="https://github.com/electron/electron/pull/$1">#$1</a>\r\n'
      )
    })
    fs.writeFileSync('_data/releases.json', JSON.stringify(body, null, 2))
  }
})
