#!/usr/bin/env node

const path = require('path')
const nugget = require('nugget')
const url = 'https://atom.io/download/electron/index.json'

var opts = {
  target: 'versions.json',
  dir: path.join(__dirname, '../_data'),
  verbose: true
}

nugget(url, opts, function (error) {
  if (error) return callback(error)
})
